name: Go test

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    name: Run Go test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: code
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: "code/go.mod"
          cache: true
          cache-dependency-path: "code/go.sum"
      - name: Run tests
        run: |-
          go test -v ./...
